name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TZ: Asia/Tokyo
    steps:
      - run: sleep 5
      - run: echo build
