name: release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # get version
      - id: get-package-version
        run: echo "::set-output name=version::$(node -p 'require(`./package`).version')"
      # main process
      - run: git worktree add ./archive archive
      - run: mktemp ./archive/XXXXXXXX
      - run: git config --global user.name 'GitHub Actions'
      - run: git config --global user.email '<>'
      - run: git add .
        working-directory: ./archive
      - run: git commit -m 'add new file'
        working-directory: ./archive
      - run: git tag archive-${{ steps.get-package-version.outputs.version }}
        working-directory: ./archive
      - run: git push origin archive archive-${{ steps.get-package-version.outputs.version }}
        working-directory: ./archive
      - run: git worktree remove ./archive
